    version: '3.8'

    services:
      # PostgreSQL Database
      postgres:
        image: postgres:16-alpine
        container_name: mobistory-postgres
        restart: unless-stopped
        environment:
          POSTGRES_USER: mobistory
          POSTGRES_PASSWORD: mobistory_dev_password
          POSTGRES_DB: mobistory_db
          PGDATA: /var/lib/postgresql/data/pgdata
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
        healthcheck:
          # CORREÇÃO: Adicionei o nome do banco de dados ao teste
          test: ["CMD-SHELL", "pg_isready -U mobistory -d mobistory_db"]
          interval: 10s
          timeout: 5s
          retries: 5
        networks:
          - mobistory-network

      # pgAdmin - Interface web para PostgreSQL
      pgadmin:
        image: dpage/pgadmin4:latest
        container_name: mobistory-pgadmin
        restart: unless-stopped
        environment:
          # CORREÇÃO: Mudei .local para .com para ser um email válido
          PGADMIN_DEFAULT_EMAIL: admin@mobistory.com
          PGADMIN_DEFAULT_PASSWORD: admin
          PGADMIN_CONFIG_SERVER_MODE: 'False'
        ports:
          - "5050:80"
        volumes:
          - pgadmin_data:/var/lib/pgadmin
        depends_on:
          - postgres
        networks:
          - mobistory-network

    volumes:
      postgres_data:
        driver: local
      pgadmin_data:
        driver: local

    networks:
      mobistory-network:
        driver: bridge
    