from .token import Token, TokenPayload
from .vehicle import (
    Vehicle,
    VehicleCreate,
    VehicleUpdate,
    VehicleWithDetails,
    Brand,
    BrandCreate,
    BrandUpdate,
    Model,
    ModelCreate,
    ModelUpdate,
    ModelVersion,
    ModelVersionCreate,
    ModelVersionUpdate,
    Color,
    ColorCreate,
    ColorUpdate,
    VehicleColor,
    VehicleColorCreate,
    VehicleCover,
    VehicleCoverCreate,
    Plate,
    PlateCreate,
)
from .conversation import (
    # Context Schemas
    ConversationContext,
    ConversationContextCreate,
    ConversationContextUpdate,
    # Conversation Schemas
    Conversation,
    ConversationCreate,
    ConversationUpdate,
    ConversationWithDetails,
    ConversationListResponse,
    ConversationDetailResponse,
    # Participant Schemas
    ConversationParticipant,
    ConversationParticipantCreate,
    ConversationParticipantUpdate,
    ConversationParticipantWithEntity,
    # Message Schemas
    ConversationMessage,
    ConversationMessageCreate,
    ConversationMessageUpdate,
    ConversationMessageWithDetails,
)
from .message import Message, MessageCreate, MessageUpdate
from .fueling import Fueling, FuelingCreate, FuelingUpdate
from .maintenance import Maintenance, MaintenanceCreate, MaintenanceUpdate

__all__ = [
    "Token",
    "TokenPayload",
    "Vehicle",
    "VehicleCreate",
    "VehicleUpdate",
    "VehicleWithDetails",
    "Brand",
    "BrandCreate",
    "BrandUpdate",
    "Model",
    "ModelCreate",
    "ModelUpdate",
    "ModelVersion",
    "ModelVersionCreate",
    "ModelVersionUpdate",
    "Color",
    "ColorCreate",
    "ColorUpdate",
    "VehicleColor",
    "VehicleColorCreate",
    "VehicleCover",
    "VehicleCoverCreate",
    "Plate",
    "PlateCreate",
    # Conversation Context
    "ConversationContext",
    "ConversationContextCreate",
    "ConversationContextUpdate",
    # Conversation
    "Conversation",
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationWithDetails",
    "ConversationListResponse",
    "ConversationDetailResponse",
    # Conversation Participant
    "ConversationParticipant",
    "ConversationParticipantCreate",
    "ConversationParticipantUpdate",
    "ConversationParticipantWithEntity",
    # Conversation Message
    "ConversationMessage",
    "ConversationMessageCreate",
    "ConversationMessageUpdate",
    "ConversationMessageWithDetails",
    "Message",
    "MessageCreate",
    "MessageUpdate",
    "Fueling",
    "FuelingCreate",
    "FuelingUpdate",
    "Maintenance",
    "MaintenanceCreate",
    "MaintenanceUpdate",
]
